"""Safety net: asserts the complete sorted list of (method, path) pairs served by the app.

Guarantees bit-identical route table during router refactoring (ARCH-001).
"""

from typing import List, Tuple
import pytest
from starlette.routing import Mount, Route
from api.main import app


def get_app_route_table(app) -> List[Tuple[str, str]]:
    """Recursively traverses the FastAPI route tree and returns sorted (method, path) tuples."""
    def extract_routes(routes, prefix=""):
        res = []
        for r in routes:
            if type(r).__name__ == "_IncludedRouter":
                sub_prefix = prefix + (r.include_context.prefix or "")
                res.extend(extract_routes(r.original_router.routes, sub_prefix))
            elif isinstance(r, Route):
                for m in (r.methods or set()):
                    if m != "HEAD":
                        res.append((m, prefix + r.path))
            elif isinstance(r, Mount):
                res.extend(extract_routes(r.routes or [], prefix + r.path))
        return res

    return sorted(set(extract_routes(app.routes)))


EXPECTED_ROUTES = [
  [
    "DELETE",
    "/api/safety/tsr/{tsr_id}"
  ],
  [
    "DELETE",
    "/api/timetable/entries/{entry_id}"
  ],
  [
    "GET",
    "/api/admin/access-requests"
  ],
  [
    "GET",
    "/api/admin/backups"
  ],
  [
    "GET",
    "/api/admin/users"
  ],
  [
    "GET",
    "/api/audit/logs"
  ],
  [
    "GET",
    "/api/audit/verify-integrity"
  ],
  [
    "GET",
    "/api/auth/me"
  ],
  [
    "GET",
    "/api/blocks/status"
  ],
  [
    "GET",
    "/api/board/kiosk"
  ],
  [
    "GET",
    "/api/board/live"
  ],
  [
    "GET",
    "/api/board/stream"
  ],
  [
    "GET",
    "/api/commercial/announcements/generate"
  ],
  [
    "GET",
    "/api/commercial/delay-certificate/verify/{qr_token}"
  ],
  [
    "GET",
    "/api/commercial/delay-certificate/{cert_no}"
  ],
  [
    "GET",
    "/api/commercial/lost-found"
  ],
  [
    "GET",
    "/api/commercial/stalls"
  ],
  [
    "GET",
    "/api/coordination/advisories/generate"
  ],
  [
    "GET",
    "/api/coordination/corridor"
  ],
  [
    "GET",
    "/api/coordination/dfc"
  ],
  [
    "GET",
    "/api/coordination/handoffs"
  ],
  [
    "GET",
    "/api/coordination/precedence"
  ],
  [
    "GET",
    "/api/handover/current"
  ],
  [
    "GET",
    "/api/handover/history"
  ],
  [
    "GET",
    "/api/infra/assets"
  ],
  [
    "GET",
    "/api/infra/cleaning-logs"
  ],
  [
    "GET",
    "/api/infra/feedback"
  ],
  [
    "GET",
    "/api/infra/rakes"
  ],
  [
    "GET",
    "/api/infra/work-orders"
  ],
  [
    "GET",
    "/api/infrastructure/assets"
  ],
  [
    "GET",
    "/api/infrastructure/cleaning-logs"
  ],
  [
    "GET",
    "/api/infrastructure/feedback"
  ],
  [
    "GET",
    "/api/infrastructure/rakes"
  ],
  [
    "GET",
    "/api/infrastructure/work-orders"
  ],
  [
    "GET",
    "/api/notifications/active"
  ],
  [
    "GET",
    "/api/ops/ad-events"
  ],
  [
    "GET",
    "/api/ops/shunting"
  ],
  [
    "GET",
    "/api/planner/changesets"
  ],
  [
    "GET",
    "/api/platform/states"
  ],
  [
    "GET",
    "/api/safety/incidents"
  ],
  [
    "GET",
    "/api/safety/lc/status"
  ],
  [
    "GET",
    "/api/safety/possessions"
  ],
  [
    "GET",
    "/api/safety/sop/active"
  ],
  [
    "GET",
    "/api/safety/sop/templates"
  ],
  [
    "GET",
    "/api/safety/tsr"
  ],
  [
    "GET",
    "/api/section/advisories/generate"
  ],
  [
    "GET",
    "/api/section/corridor"
  ],
  [
    "GET",
    "/api/section/dfc"
  ],
  [
    "GET",
    "/api/section/handoffs"
  ],
  [
    "GET",
    "/api/section/precedence"
  ],
  [
    "GET",
    "/api/system/model-info"
  ],
  [
    "GET",
    "/api/system/status"
  ],
  [
    "GET",
    "/api/timetable/versions"
  ],
  [
    "GET",
    "/api/timetable/versions/{version_id}/entries"
  ],
  [
    "GET",
    "/api/timetable/versions/{version_id}/validate"
  ],
  [
    "GET",
    "/api/v1/cascade/ripple"
  ],
  [
    "GET",
    "/api/v1/conflicts/{train_no}"
  ],
  [
    "GET",
    "/api/v1/corridor/congestion-radar"
  ],
  [
    "GET",
    "/api/v1/crew/alerts"
  ],
  [
    "GET",
    "/api/v1/demo/comparator"
  ],
  [
    "GET",
    "/api/v1/demo/shocks"
  ],
  [
    "GET",
    "/api/v1/demo/time-machine"
  ],
  [
    "GET",
    "/api/v1/evaluation/summary"
  ],
  [
    "GET",
    "/api/v1/health"
  ],
  [
    "GET",
    "/api/v1/ledger/scoreboard"
  ],
  [
    "GET",
    "/api/v1/ledger/verify"
  ],
  [
    "GET",
    "/api/v1/live/events/recent"
  ],
  [
    "GET",
    "/api/v1/live/positions"
  ],
  [
    "GET",
    "/api/v1/live/stream"
  ],
  [
    "GET",
    "/api/v1/meta/clock"
  ],
  [
    "GET",
    "/api/v1/meta/config"
  ],
  [
    "GET",
    "/api/v1/meta/models"
  ],
  [
    "GET",
    "/api/v1/meta/stations"
  ],
  [
    "GET",
    "/api/v1/meta/trains"
  ],
  [
    "GET",
    "/api/v1/model/performance"
  ],
  [
    "GET",
    "/api/v1/network/state"
  ],
  [
    "GET",
    "/api/v1/passenger/pnr/{pnr}"
  ],
  [
    "GET",
    "/api/v1/passenger/popular"
  ],
  [
    "GET",
    "/api/v1/passenger/search"
  ],
  [
    "GET",
    "/api/v1/passenger/snapshot"
  ],
  [
    "GET",
    "/api/v1/passenger/stream"
  ],
  [
    "GET",
    "/api/v1/pnr/{pnr_no}"
  ],
  [
    "GET",
    "/api/v1/stations/{code}"
  ],
  [
    "GET",
    "/api/v1/stations/{code}/connections"
  ],
  [
    "GET",
    "/api/v1/stations/{code}/gantt"
  ],
  [
    "GET",
    "/api/v1/trains/{train_no}/autopsy"
  ],
  [
    "GET",
    "/api/v1/trains/{train_no}/eta"
  ],
  [
    "GET",
    "/api/v1/trains/{train_no}/journey"
  ],
  [
    "GET",
    "/api/v1/trains/{train_no}/live"
  ],
  [
    "GET",
    "/api/v1/trains/{train_no}/why-late"
  ],
  [
    "GET",
    "/api/workforce/breathalyzer"
  ],
  [
    "GET",
    "/api/workforce/crew/breaches"
  ],
  [
    "GET",
    "/api/workforce/crew/roster"
  ],
  [
    "GET",
    "/api/workforce/sahayak"
  ],
  [
    "GET",
    "/api/workforce/shifts"
  ],
  [
    "GET",
    "/docs"
  ],
  [
    "GET",
    "/docs/oauth2-redirect"
  ],
  [
    "GET",
    "/healthz"
  ],
  [
    "GET",
    "/metrics"
  ],
  [
    "GET",
    "/openapi.json"
  ],
  [
    "GET",
    "/readyz"
  ],
  [
    "GET",
    "/redoc"
  ],
  [
    "GET",
    "/v1/cascade/ripple"
  ],
  [
    "GET",
    "/v1/conflicts/{train_no}"
  ],
  [
    "GET",
    "/v1/corridor/congestion-radar"
  ],
  [
    "GET",
    "/v1/crew/alerts"
  ],
  [
    "GET",
    "/v1/demo/comparator"
  ],
  [
    "GET",
    "/v1/demo/shocks"
  ],
  [
    "GET",
    "/v1/demo/time-machine"
  ],
  [
    "GET",
    "/v1/evaluation/summary"
  ],
  [
    "GET",
    "/v1/health"
  ],
  [
    "GET",
    "/v1/ledger/scoreboard"
  ],
  [
    "GET",
    "/v1/ledger/verify"
  ],
  [
    "GET",
    "/v1/live/events/recent"
  ],
  [
    "GET",
    "/v1/live/positions"
  ],
  [
    "GET",
    "/v1/live/stream"
  ],
  [
    "GET",
    "/v1/meta/clock"
  ],
  [
    "GET",
    "/v1/meta/config"
  ],
  [
    "GET",
    "/v1/meta/models"
  ],
  [
    "GET",
    "/v1/meta/stations"
  ],
  [
    "GET",
    "/v1/meta/trains"
  ],
  [
    "GET",
    "/v1/model/performance"
  ],
  [
    "GET",
    "/v1/network/state"
  ],
  [
    "GET",
    "/v1/passenger/pnr/{pnr}"
  ],
  [
    "GET",
    "/v1/passenger/popular"
  ],
  [
    "GET",
    "/v1/passenger/search"
  ],
  [
    "GET",
    "/v1/passenger/snapshot"
  ],
  [
    "GET",
    "/v1/passenger/stream"
  ],
  [
    "GET",
    "/v1/pnr/{pnr_no}"
  ],
  [
    "GET",
    "/v1/stations/{code}"
  ],
  [
    "GET",
    "/v1/stations/{code}/connections"
  ],
  [
    "GET",
    "/v1/stations/{code}/gantt"
  ],
  [
    "GET",
    "/v1/trains/{train_no}/autopsy"
  ],
  [
    "GET",
    "/v1/trains/{train_no}/eta"
  ],
  [
    "GET",
    "/v1/trains/{train_no}/journey"
  ],
  [
    "GET",
    "/v1/trains/{train_no}/live"
  ],
  [
    "GET",
    "/v1/trains/{train_no}/why-late"
  ],
  [
    "POST",
    "/api/access-requests"
  ],
  [
    "POST",
    "/api/admin/backups/create"
  ],
  [
    "POST",
    "/api/admin/backups/verify"
  ],
  [
    "POST",
    "/api/admin/users"
  ],
  [
    "POST",
    "/api/auth/change-password"
  ],
  [
    "POST",
    "/api/auth/login"
  ],
  [
    "POST",
    "/api/auth/logout"
  ],
  [
    "POST",
    "/api/auth/refresh"
  ],
  [
    "POST",
    "/api/blocks/{block_id}/line-clear"
  ],
  [
    "POST",
    "/api/blocks/{block_id}/state"
  ],
  [
    "POST",
    "/api/commercial/delay-certificate"
  ],
  [
    "POST",
    "/api/commercial/lost-found"
  ],
  [
    "POST",
    "/api/commercial/stalls"
  ],
  [
    "POST",
    "/api/coordination/advisories/{adv_id}/execute"
  ],
  [
    "POST",
    "/api/coordination/handoff/request"
  ],
  [
    "POST",
    "/api/handover/draft"
  ],
  [
    "POST",
    "/api/handover/{handover_id}/ack-in"
  ],
  [
    "POST",
    "/api/handover/{handover_id}/sign-out"
  ],
  [
    "POST",
    "/api/infra/assets"
  ],
  [
    "POST",
    "/api/infra/cleaning-logs"
  ],
  [
    "POST",
    "/api/infra/rakes"
  ],
  [
    "POST",
    "/api/infra/work-orders"
  ],
  [
    "POST",
    "/api/infrastructure/assets"
  ],
  [
    "POST",
    "/api/infrastructure/cleaning-logs"
  ],
  [
    "POST",
    "/api/infrastructure/rakes"
  ],
  [
    "POST",
    "/api/infrastructure/work-orders"
  ],
  [
    "POST",
    "/api/notifications/emit"
  ],
  [
    "POST",
    "/api/notifications/escalate"
  ],
  [
    "POST",
    "/api/notifications/{notification_id}/ack"
  ],
  [
    "POST",
    "/api/ops/setin/{train_no}"
  ],
  [
    "POST",
    "/api/ops/setout/{train_no}"
  ],
  [
    "POST",
    "/api/ops/shunting"
  ],
  [
    "POST",
    "/api/planner/apply"
  ],
  [
    "POST",
    "/api/planner/simulate"
  ],
  [
    "POST",
    "/api/platform/assign"
  ],
  [
    "POST",
    "/api/platform/assignments/{assign_id}/lock"
  ],
  [
    "POST",
    "/api/platform/block"
  ],
  [
    "POST",
    "/api/platform/reoptimize"
  ],
  [
    "POST",
    "/api/safety/incidents"
  ],
  [
    "POST",
    "/api/safety/possession/request"
  ],
  [
    "POST",
    "/api/safety/possession/{possession_id}/grant"
  ],
  [
    "POST",
    "/api/safety/possession/{possession_id}/restore"
  ],
  [
    "POST",
    "/api/safety/sop/start"
  ],
  [
    "POST",
    "/api/safety/sop/{run_id}/step"
  ],
  [
    "POST",
    "/api/safety/tsr"
  ],
  [
    "POST",
    "/api/section/advisories/{adv_id}/execute"
  ],
  [
    "POST",
    "/api/section/handoff/request"
  ],
  [
    "POST",
    "/api/timetable/entries"
  ],
  [
    "POST",
    "/api/timetable/versions"
  ],
  [
    "POST",
    "/api/timetable/versions/{version_id}/import-seed"
  ],
  [
    "POST",
    "/api/timetable/versions/{version_id}/publish"
  ],
  [
    "POST",
    "/api/v1/advise"
  ],
  [
    "POST",
    "/api/v1/advise/{adv_id}/ack"
  ],
  [
    "POST",
    "/api/v1/demo/inject-event"
  ],
  [
    "POST",
    "/api/v1/demo/reset-events"
  ],
  [
    "POST",
    "/api/v1/demo/time"
  ],
  [
    "POST",
    "/api/v1/hooks/whatsapp"
  ],
  [
    "POST",
    "/api/v1/simulate/what-if"
  ],
  [
    "POST",
    "/api/v1/stations/{code}/reoptimize"
  ],
  [
    "POST",
    "/api/workforce/breathalyzer"
  ],
  [
    "POST",
    "/api/workforce/crew/sign-on"
  ],
  [
    "POST",
    "/api/workforce/crew/{roster_id}/sign-off"
  ],
  [
    "POST",
    "/api/workforce/shifts"
  ],
  [
    "POST",
    "/demo/time"
  ],
  [
    "POST",
    "/v1/advise"
  ],
  [
    "POST",
    "/v1/advise/{adv_id}/ack"
  ],
  [
    "POST",
    "/v1/demo/inject-event"
  ],
  [
    "POST",
    "/v1/demo/reset-events"
  ],
  [
    "POST",
    "/v1/demo/time"
  ],
  [
    "POST",
    "/v1/hooks/whatsapp"
  ],
  [
    "POST",
    "/v1/simulate/what-if"
  ],
  [
    "POST",
    "/v1/stations/{code}/reoptimize"
  ],
  [
    "PUT",
    "/api/admin/access-requests/{request_id}"
  ],
  [
    "PUT",
    "/api/admin/users/{user_id}"
  ],
  [
    "PUT",
    "/api/commercial/lost-found/{item_id}/claim"
  ],
  [
    "PUT",
    "/api/coordination/handoff/{lock_id}/grant"
  ],
  [
    "PUT",
    "/api/coordination/handoff/{lock_id}/release"
  ],
  [
    "PUT",
    "/api/infra/work-orders/{wo_id}/resolve"
  ],
  [
    "PUT",
    "/api/infrastructure/work-orders/{wo_id}/resolve"
  ],
  [
    "PUT",
    "/api/ops/shunting/{move_id}/status"
  ],
  [
    "PUT",
    "/api/safety/lc/{lc_id}/status"
  ],
  [
    "PUT",
    "/api/section/handoff/{lock_id}/grant"
  ],
  [
    "PUT",
    "/api/section/handoff/{lock_id}/release"
  ],
  [
    "PUT",
    "/api/timetable/entries/{entry_id}"
  ],
  [
    "PUT",
    "/api/workforce/sahayak/{sahayak_id}/duty"
  ]
]


def test_app_route_table_snapshot():
    """Asserts that the application serves the exact expected list of (method, path) routes."""
    current_routes = [list(r) for r in get_app_route_table(app)]

    missing_routes = [r for r in EXPECTED_ROUTES if r not in current_routes]
    extra_routes = [r for r in current_routes if r not in EXPECTED_ROUTES]

    assert not missing_routes, f"Missing routes in app: {missing_routes}"
    assert not extra_routes, f"Unexpected extra routes in app: {extra_routes}"
    assert current_routes == EXPECTED_ROUTES
