import React from 'react';
import { Link } from 'react-router-dom';
import { SEO } from '@/lib/seo';
import { SITE } from '@/config/site';
import { ArrowLeft, ShieldAlert } from 'lucide-react';

export const TermsPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-bg text-text-main font-sans flex flex-col justify-between selection:bg-accent selection:text-bg">
      <SEO
        title="Terms of Use"
        description="Terms of use, including the advisory-only operational disclaimer."
        canonicalPath="/terms"
      />

      {/* Header */}
      <header className="border-b border-hairline py-4 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2 font-mono font-bold text-sm text-text-main hover:text-accent transition-colors">
            <span className="w-2 h-2 bg-accent inline-block" />
            <span>{SITE.name}</span>
          </Link>
          <Link to="/" className="text-xs font-mono text-text-dim hover:text-text-main flex items-center gap-1">
            <ArrowLeft className="w-3.5 h-3.5 stroke-[1.5]" />
            <span>Home</span>
          </Link>
        </div>
      </header>

      {/* Content: Max-width 68ch per §15 */}
      <main className="max-w-[68ch] mx-auto w-full px-4 py-12 space-y-8 text-xs sm:text-[13px] leading-relaxed">
        <div className="space-y-2 border-b border-hairline pb-6">
          <div className="text-xs font-mono text-accent uppercase tracking-wider">
            Operational Agreements
          </div>
          <h1 className="text-2xl font-bold font-sans tracking-tight text-text-main">
            Terms of Use
          </h1>
          <p className="text-xs text-text-dim font-mono">
            Smart India Hackathon 2026 · Operational Safety Specification
          </p>
        </div>

        {/* Prominent Operational Disclaimer Box */}
        <div className="p-4 bg-warn/10 border-2 border-warn text-text-main space-y-2 font-mono text-xs">
          <div className="flex items-center gap-2 font-bold text-warn uppercase">
            <ShieldAlert className="w-4 h-4 stroke-[2]" />
            <span>Operational Advisory-Only Safety Notice</span>
          </div>
          <p className="font-sans text-xs text-text-main leading-relaxed">
            {SITE.disclaimer}. RailTwin-X provides algorithmic decision support, delay forecasts, and platform optimization recommendations. All platform routing, signal clearing, speed caution orders, and crew assignments must be authorized by qualified human railway personnel in accordance with Indian Railways General and Subsidiary Rules (G&SR).
          </p>
        </div>

        <section className="space-y-3">
          <h2 className="text-base font-bold font-sans text-text-main">
            1. Scope of Service
          </h2>
          <p className="text-text-dim">
            RailTwin-X is a decision-support prototype developed for station masters, section controllers, and railway operations staff. The software predicts train arrival bands, identifies headway conflicts, and assists in optimal dispatching.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold font-sans text-text-main">
            2. Decision Verification & Human-in-the-Loop
          </h2>
          <p className="text-text-dim">
            Every advisory generated by RailTwin-X requires explicit human acceptance before execution. The platform maintains a complete regulatory audit log of all human interactions, overrides, and timestamps.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold font-sans text-text-main">
            3. Disclaimer of Physical Control
          </h2>
          <p className="text-text-dim">
            Under no circumstances does RailTwin-X interface directly with physical electronic interlocking (EI), solid-state relay interlockings, or automatic block signaling relays.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-base font-bold font-sans text-text-main">
            4. Contact
          </h2>
          <div className="p-3 bg-panel border border-hairline font-mono text-xs text-text-main space-y-1">
            <div>{SITE.teamName}</div>
            <div>{SITE.address}</div>
            <div>Email: <a href={`mailto:${SITE.email}`} className="text-accent underline">{SITE.email}</a></div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-hairline py-4 px-4 text-center text-[11px] font-mono text-text-dim">
        {SITE.disclaimer}
      </footer>
    </div>
  );
};
