/** @type {irmport('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        paper: '#F3EFE6',
        surface: '#FDFCF8',
        raised: '#ECE7DB',
        line: '#E1DAC9',
        lineStrong: '#C8C0AC',
        ink: '#191712',
        ink2: '#57534A',
        ink3: '#6F6A5C',
        ochre: '#C25E00',
        ochreDeep: '#8A4B00',
        ochreWash: 'rgba(194, 94, 0, 0.10)',
        clear: '#1B6B3A',
        caution: '#B87400',
        restrict: '#B3362B',
        graphite: '#4A453D',
        kioskBg: '#000000',
        kioskGold: '#FFD700',
        kioskText: '#FFFFFF',
        nightBg0: '#0A0B0D',
        nightBg1: '#101216',
        nightLine: '#23272F',
        nightAmber: '#F5A524',
        nightGreen: '#3DDC97',
        nightRed: '#F4506A',
      },
      fontFamily: {
        display: ['\"Fraunces\"', 'Georgia', 'serif'],
        sans: ['\"Instrument Sans\"', 'system-ui', 'sans-serif'],
        mono: ['\"IBM Plex Mono\"', 'monospace'],
        hindi: ['\"Noto Sans Devanagari\"', 'sans-serif'],
      },
      fontSize: {
        micro: ['11px', { lineHeight: '14px', letterSpacing: '0.08em' }],
        caption: ['13px', { lineHeight: '18px' }],
        body: ['15px', { lineHeight: '22px' }],
        subhead: ['20px', { lineHeight: '26px' }],
        headline: ['32px', { lineHeight: '38px' }],
        hero: ['60px', { lineHeight: '64px' }],
      },
      borderRadius: {
        sm: '2px',
        DEFAULT: '4px',
        md: '4px',
        lg: '4px',
        none: '0px',
      },
    },
  },
  plugins: [],
};
